name: Test optan without gui

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py